[package]
name = "Size"
version = "0.1.0"
edition = "2021"

[[bin]] # binary target
name = "Size"
path = "src/main.rs"


[dependencies]
r-efi = "5.0.0"
#RustBootServicesAllocatorDxe = {git = "https://github.com/microsoft/mu_plus.git"}
